
services:
  reservation:
    image: reservation:latest
    #image: reservation-aot:latest
    environment:
      spring.kafka.bootstrap-servers: kafka:29092
      spring.datasource.url: jdbc:postgresql://postgres:5432/reservation
    ports:
      - 8080:8080
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: reservation-network